version: '3'

services:
  web:
    image: nikhilgoenka/ecommerce-backend:1.0.0
    container_name: ecommerce-backend
    command: bash -c "python3.8 manage.py collectstatic --no-input && gunicorn ecommerce.wsgi:application --bind 0.0.0.0:3005"
    ports:
      - 3005:3005
    networks:
      - nginx_network
    volumes:
     - static:/static
    restart: always

  web_2:
    container_name: latest-ecommerce-backend
    image: nikhilgoenka/ecommerce-backend:${DT_RELEASE_VERSION}
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - DT_RELEASE_VERSION=$DT_RELEASE_VERSION
    command: bash -c "python3.8 manage.py collectstatic --no-input && gunicorn ecommerce.wsgi:application --bind 0.0.0.0:3005"
    ports:
      - 3006:3005
    networks:
      - nginx_network
    volumes:
     - static:/static
    restart: always

  nginx:
    image: nikhilgoenka/ecommerce-frontend
    container_name: ecommerce-frontend-loadbalancer
    ports:
      - 80:80
    volumes:
     - static:/static
    depends_on:
      - web
    networks:
      - nginx_network
    restart: always
networks:
   nginx_network:
      driver: bridge
volumes:
   static:
