apiVersion: apps/v1
kind: Deployment
metadata:
 name: ecommerce-backend
 namespace: ecommerce
spec:
 selector:
   matchLabels:
     run: frontend
 template:
   metadata:
     labels:
       run: frontend
   spec:
     containers:
     - args:
       - bash
       - -c
       - python3.8 manage.py collectstatic --no-input && gunicorn ecommerce.wsgi:application --bind 0.0.0.0:3005
       name: frontend
       image: nikhilgoenka/ecommerce-backend:latest
       imagePullPolicy: IfNotPresent 
       ports:
       - containerPort: 30050
         protocol: TCP
