#!/bin/bash

# Name of the application
NAME="ecommerce"
# Django project directory
DJANGODIR=/home/d1prumworkshop/clone-4/django-ecommerce-website/src
# we will communicte using this unix socket
SOCKFILE=/home/d1prumworkshop/clone-4/django-ecommerce-website/src/ecommerce/run/gunicorn.sock
# the user to run as
USER=root
# the group to run as
GROUP=root
# how many worker processes should Gunicorn spawn
NUM_WORKERS=3
# which settings file should Django use
DJANGO_SETTINGS_MODULE=ecommerce.settings
# WSGI module name
DJANGO_WSGI_MODULE=ecommerce.wsgi
echo "Starting $NAME as `whoami`"
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec ../bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--user=$USER --group=$GROUP \
--bind=unix:$SOCKFILE \
--log-level=debug \
--log-file=-

